name: Test, Build, and Push Docker Image

on:
  push:
    branches:
      - main
    paths:
      - "public/**" # Changes of the website files trigger the workflow

jobs:
  # Test job
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Install HTMLHint
        run: npm install -g htmlhint

      - name: Run HTML linting
        run: htmlhint "public/**/*.html"

      - name: Install Stylelint
        run: npm install -g stylelint stylelint-config-standard

      - name: Run CSS linting
        run: stylelint "public/css/**/*.css"

      - name: Install ESLint
        run: npm install -g eslint

      - name: Run JavaScript linting
        run: eslint "public/js/**/*.js" --config eslint.config.js

  # Deploy and push job
  build-and-push:
    runs-on: ubuntu-latest
    needs: test # Waits for the test job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU # Enables multi-architecture builds to build Docker images for different CPU architectures
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx # Enables advanced Buildx Docker BuildKit build engine
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub # Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4 # Requires Buildx
        with:
          push: true
          context: .  # Include the Dockerfile directory
          file: Dockerfiles/Dockerfile # Path to the Dockerfile
          tags: |
            jueklu/github-actions-static-website:latest
            jueklu/github-actions-static-website:${{ github.sha }}
